default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: admin
  socket: /data/mysql/mysql.sock
  reconnect: true

development:
  <<: *default
  database: mycookbook_dev

test:
  <<: *default
  database: mycookbook_test

production:
  <<: *default
  database: mycookbook
